import type { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";
import { Space_Mono } from "next/font/google";
import { ChatProvider } from "./components/chatContent";

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#232325] text-gray-900">
        <ChatProvider>{children}</ChatProvider>
      </body>
    </html>
  );
}
