import type { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";
import { JetBrains_Mono } from "next/font/google";
import { ChatProvider } from "./components/chatContent";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-jetbrains-mono",
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} min-h-screen bg-[#0d0d0d] text-[rgba(242,243,245,0.92)]`}
      >
        <ChatProvider>{children}</ChatProvider>
      </body>
    </html>
  );
}
